baseURL = 'https://guaraproductions.github.io/guara-docs/'
languageCode = 'pt-br'
title = 'Guara Help Site'

[params]
  description = "Um site est√°tico para ajudar desenvolvedores no Godot"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
