baseURL = 'https://guaraproductions.github.io/guara-docs/'
title = 'Guara Docs'
theme = 'tailbliss'
enableEmoji = true
enableRobotsTXT = true

languageCode = "pt-br"
defaultContentLanguage = "pt-br"
defaultContentLanguageInSubdir = true

[params]
  description = "Um site estático para ajudar desenvolvedores no Godot"
  disable_theme_toggle = false
  favicon = false
  svg = true
  faviconVersion = "1"

[languages]
  [languages.pt-br]
    languageName = "Português do Brasil"
    weight = 1
    contentDir = "content/pt-br"
  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"

[module]
  [[module.imports]]
    path = "github.com/hugo-mods/icons"