baseURL = 'https://guaraproductions.github.io/guara-docs/'
title = 'Guara Docs'
theme = 'tailbliss'
enableEmoji = true
enableRobotsTXT = true

[params]
  description = "Um site estático para ajudar desenvolvedores no Godot"
  disable_theme_toggle = false
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

languageCode = "pt-BR"
defaultContentLanguage = "pt-BR"

[languages]
  [languages.pt-BR]
    languageName = "Português do Brasil"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2
